implement choose file flag for view log
- implement choose file flag and choose file function
- update README.md and .gitignore

diff --git a/bin/kflog b/bin/kflog
--- a/bin/kflog
+++ b/bin/kflog
@@ -6,6 +6,7 @@ TAIL_LINES=0
 DEFAULT_TAIL_LINES=500
 IS_LIVE_TAIL=false
 IS_VIEW_LOG=false
+IS_CHOOSE_FILE=false
 
 # ------------- functions -------------
 # fzfx is a wrapper for fzf with header and header-border
@@ -13,22 +14,24 @@ fzfx() {
   fzf --header="$1" --header-border=double
 }
 
-# download_logs downloads logs from a pod and saves them to a file
+# Downloads logs from a pod, saves them to a file, and opens the file in a viewer
 download_logs() {
-  DIR=$HOME/Documents/inbox/k8s-logs
-  mkdir -p $DIR
+  # LOG_DIR=$HOME/Documents/inbox/k8s-logs
+  source $HOME/zsh-tools/envs/kflog/.env
+
+  mkdir -p $LOG_DIR
   FILENAME="$PODNAME-$(date +%Y%m%d-%H%M%S).log"
   
-  echo "Saving logs to $DIR/$FILENAME"
+  echo "Saving logs to $LOG_DIR/$FILENAME"
   
   # Download logs from the pod base on the tail lines
   if [[ $TAIL_LINES -gt 0 ]]; then
-    kubectl logs $PODNAME -n $NAMESPACE --tail $TAIL_LINES > "$DIR/$FILENAME"
+    kubectl logs $PODNAME -n $NAMESPACE --tail $TAIL_LINES > "$LOG_DIR/$FILENAME"
   else
-    kubectl logs $PODNAME -n $NAMESPACE > "$DIR/$FILENAME"
+    kubectl logs $PODNAME -n $NAMESPACE > "$LOG_DIR/$FILENAME"
   fi
 
-  echo "Downloaded logs to $DIR/$FILENAME"
+  echo "Downloaded logs to $LOG_DIR/$FILENAME"
 
   read -p "Open logs in viewer? [Y/n] " choice # Ask for confirmation to open logs in a viewer
   
@@ -38,13 +41,13 @@ download_logs() {
       viewer=$(printf "plain\nbat\nlnav\nquit" | fzfx "Choose a viewer") # Ask for a viewer
       case "$viewer" in
         plain)
-          cat "$DIR/$FILENAME"
+          cat "$LOG_DIR/$FILENAME"
           ;;
         bat)
-          bat "$DIR/$FILENAME"
+          bat "$LOG_DIR/$FILENAME"
           ;;
         nvim)
-          nvim "$DIR/$FILENAME"
+          nvim "$LOG_DIR/$FILENAME"
           ;;
         quit)
           exit 0
@@ -57,6 +60,7 @@ download_logs() {
   fi
 }
 
+# Live tail logs
 live_logs() {
   tmpfile=$(mktemp /tmp/k8slog.xxxxx.log) # Create a temporary file to store the logs
 
@@ -81,12 +85,13 @@ live_logs() {
   esac
 }
 
+# View logs without downloading
 view_log() {
   viewer=$(printf "plain\nbat\nquit" | fzfx "Choose a viewer") # Ask for a viewer
-  cmd="kubectl logs $PODNAME -n $NAMESPACE"
+  cmd="kubectl logs $PODNAME -n $NAMESPACE" # Build the command to run
 
   if [[ $TAIL_LINES -gt 0 ]]; then
-    cmd="$cmd --tail $TAIL_LINES"
+    cmd="$cmd --tail $TAIL_LINES" # Add tail lines if specified
   fi
 
   case "$viewer" in
@@ -95,6 +100,31 @@ view_log() {
       ;;
     bat)
       eval "$cmd" | bat
+      ;;
+    quit)
+      exit 0
+      ;;
+    *)
+      echo "Invalid choice"
+      exit 1
+      ;;
+  esac
+}
+
+# Choose a log file and open it in a viewer
+choose_log() {
+  # LOG_DIR=$HOME/Documents/inbox/k8s-logs
+  source $HOME/zsh-tools/envs/kflog/.env
+
+  FILENAME=$(ls "$LOG_DIR" | fzfx "Choose a log file")
+
+  viewer=$(printf "plain\nbat\nquit" | fzfx "Choose a viewer") # Ask for a viewer
+  case "$viewer" in
+    plain)
+      cat "$LOG_DIR/$FILENAME"
+      ;;
+    bat)
+      bat "$LOG_DIR/$FILENAME"
       ;;
     quit)
       exit 0
@@ -147,6 +177,10 @@ while [[  $# -gt 0 ]]; do
       IS_VIEW_LOG=true
       shift
       ;;
+    -cf|--choose-file)
+      IS_CHOOSE_FILE=true
+      shift
+      ;;
     *)
       echo "Unknown option $1"
       break 
@@ -154,20 +188,24 @@ while [[  $# -gt 0 ]]; do
   esac
 done
 
-kubectx | fzfx "Choose a cluster" # Choose cluster
-PODINFO=$(kubectl get pods -A | fzfx "Choose a pod") # Choose pod
-
-IFS=' ' read -r -a POD <<< "$PODINFO" # Split the pod info into an array
-
-NAMESPACE=${POD[0]}
-PODNAME=${POD[1]}
-
-echo "Choose pod: $PODNAME, namespace: $NAMESPACE"
-
-if [[ $IS_LIVE_TAIL == true ]]; then
-  live_logs
-elif [[ $IS_VIEW_LOG == true ]]; then
-  view_log
+if [[ $IS_CHOOSE_FILE == true ]]; then
+  choose_log
 else
-  download_logs
+  kubectx "$(kubectx | fzfx "Choose a cluster")" # Choose cluster
+  PODINFO=$(kubectl get pods -A | fzfx "Choose a pod") # Choose pod
+  
+  IFS=' ' read -r -a POD <<< "$PODINFO" # Split the pod info into an array
+  
+  NAMESPACE=${POD[0]}
+  PODNAME=${POD[1]}
+  
+  echo "Choose pod: $PODNAME, namespace: $NAMESPACE"
+  
+  if [[ $IS_LIVE_TAIL == true ]]; then
+    live_logs
+  elif [[ $IS_VIEW_LOG == true ]]; then
+    view_log
+  else
+    download_logs
+  fi
 fi
